version: '3.8'
services:

  redis:
    image: redis:alpine

  app:
    build: .
    volumes:
      - .:/django_rest
    ports:
      - 8000:8000
    image: app:django_rest
    container_name: rest_docker
    command: python manage.py runserver 0.0.0.0:8000

  celery:
    build: .
    command: celery -A celery_django.celery worker --pool=solo -l info
    volumes:
      - .:/django_rest
    depends_on:
      - redis

  celery-beat:
    build: .
    command: celery -A celery_django beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/django_rest
    depends_on:
      - redis


