# Generated by Django 4.2.4 on 2023-08-12 08:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='expiration_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 8, 12, 8, 44, 48, 521164, tzinfo=datetime.timezone.utc)),
        ),
    ]
