# Generated by Django 4.1.7 on 2023-09-04 08:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_story_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='expiration_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 9, 4, 8, 41, 34, 420885, tzinfo=datetime.timezone.utc)),
        ),
    ]
