# Generated by Django 4.1.7 on 2023-09-06 04:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_story_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='expiration_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 9, 6, 5, 3, 17, 744649, tzinfo=datetime.timezone.utc)),
        ),
    ]
